"""Domain models for worker alerting pipeline."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class AlertCheckDescriptor:
    """Declarative checker configuration loaded from KDL.

    Args:
        name: Stable checker name.
        check_type: Checker implementation type.
        interval_seconds: Polling interval in seconds.
        enabled: Whether checker is enabled.
    """

    name: str
    check_type: str
    interval_seconds: int
    enabled: bool


@dataclass(frozen=True)
class AlertEvent:
    """Alert event generated by monitor checks.

    Args:
        key: Stable deduplication key.
        title: Human-readable short title.
        details: Detailed alert text.
        is_firing: True for firing event, False for recovery event.
    """

    key: str
    title: str
    details: str
    is_firing: bool


@dataclass(frozen=True)
class AlertState:
    """Persistent alert state for deduplication.

    Args:
        key: Stable deduplication key.
        is_firing: Last observed firing state.
    """

    key: str
    is_firing: bool
